server:
  port: 8086
  servlet:
    context-path: /mail
    
spring:
  application:
    name: mail
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#     dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/mail?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSl=false
    username: root
    password: Admin357/  

  rabbitmq:
    host: localhost 
    port: 5672
    username: root
    password: Admin357/ 
        
crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue          

auth:
  rabbitmq:
    exchange: auth.exchange
    queue: auth.user.queue   

security:
  jwt:
    token: 
      secret-key: chave_microservices
      
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka